### ISSUE TITLE
Selfhost?

### ISSUE THREAD

**Issue by louanfontenele** [gravesoft/msdl#5]
Is it possible to selfhost?

**Comment by thecatontheceiling** [comment]
Yes but why would you

**Comment by louanfontenele** [comment]
> Yes but why would you

I'm trying to create a version in my language but unfortunately it's not working. When I request to download it, I get an error.

**Comment by ave9858** [comment]
the repo is just a collection of static files, you should be able to host it anywhere.

**Comment by louanfontenele** [comment]
> the repo is just a collection of static files, you should be able to host it anywhere.

![image](https://github.com/user-attachments/assets/8fea6f51-ea1a-42f5-80a8-0f98b5879800)

I got this error, this is why i ask here if i can self host

**Comment by louanfontenele** [comment]
well, for some reason, i even dont know how and why, the link appers, even by the error.

**Comment by ave9858** [comment]
> well, for some reason, i even dont know how and why, the link appers, even by the error.

Because it used a fallback method after the previous method failed. If you get a failure that isn't automatically corrected, just report it here or in the discord.
