### ISSUE TITLE
Proxy returning json response instead of download link only

### ISSUE THREAD

**Issue by RadNotRed** [gravesoft/msdl#8]
When sentinel denies a request, it goes through the proxy which then will provide a json response of the download uri and other information instead of instantly download and/or giving the "Download x64 iso" button, not sure if this is intended or is a bug, but I'd figured i'd ask 
This also happens and may cause confusion on the windows 10 one where there's both x32 and x64 links in the same json reply 

![image](https://github.com/user-attachments/assets/0af456d1-5410-4b19-a42f-21af3c1a0f41)

**Comment by thecatontheceiling** [comment]
Intended. Nobody at gravesoft has bothered to fix it yet. I'll probably pick it up tomorrow or something

**Comment by RadNotRed** [comment]
cool, thanks !

**Comment by thecatontheceiling** [comment]
Fixed. @ave9858 pls close
